['AFK Stages']
Attempts = 1
Formations = 7
'Skip Manual Formations' = false
'Spend Gold' = false
'Start with current Formation' = true
'Suggested Formations' = true

['Arcane Labyrinth']
Difficulty = 15
'Key Quota' = 2700

['Claim AFK Rewards']
'Claim Stage Rewards' = false

['Custom Routine 1']
'Display Name' = 'Stages + Trials'
Repeat = true
'Task List' = ['Season Legend Trial', 'Season Talent Stages', 'AFK Stages', 'Claim AFK Rewards', 'Level Up All Heroes', 'Equip new Equipment']

['Custom Routine 2']
'Display Name' = 'Stages'
Repeat = true
'Task List' = ['Season Talent Stages', 'AFK Stages', 'Claim AFK Rewards', 'Equip new Equipment', 'Level Up All Heroes']

['Custom Routine 3']
'Display Name' = 'All'
Repeat = true
'Task List' = ['Season Talent Stages', 'AFK Stages', 'Claim AFK Rewards', 'Equip new Equipment', 'Level Up All Heroes', 'Season Legend Trial', 'Level Up All Heroes', 'Arcane Labyrinth', "Dura's Trials"]

[Dailies]
'Arena Battle' = false
'Buy All Affinity' = false
'Buy Discount Affinity' = true
'Buy Temporal Essences' = false
'Essence Buy Count' = 1
'Single Pull' = false

['Dream Realm']
'Spend Gold' = false

["Dura's Trials"]
Attempts = 1
Formations = 7
'Spend Gold' = false
'Start with current Formation' = true
'Suggested Formations' = true

[General]
'Assist Limit' = 20
'Exclude Heroes' = []

['Legend Trial']
Attempts = 1
Formations = 7
'Skip Manual Formations' = false
'Spend Gold' = false
'Start with current Formation' = true
'Suggested Formations' = true
Towers = ['Lightbearer', 'Wilder', 'Graveborn', 'Mauler']

['Titan Reaver Proxy Battles']
'Titan Reaver Proxy Battle Limit' = 50
